api/urls.py
from django.urls import path

from api.views import ProductListView, ProductDetailView
app_name ='api'

urlpatterns = [
    path('products/', ProductListView.as_view(), name='product_list_api'),
    path('products/<pk>', ProductDetailView.as_view(), name='product_detail_api')
]

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='c'),
    path('add/<int:product_id>/', views.cart_add, name='card_add'),
    path('remove/<int:product_id>', views.cart_remove, name = 'cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views


app_name = 'coupons'


urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

myshop/urls.py
from django.urls import path
from . import views


app_name ='myshop'

urlpatterns = [
    path('',views.product_list, name ='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('tag/<slug:tag_slug>/', views.product_list, name='product_list_by_tag'),
    path('like/', views.product_like, name='product_like'),


]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('history-order/', views.orders_history, name='history'),
    path('detail-order/<int:id>', views.detail_order, name='detail_order')




]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from myshop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('myshop.urls', namespace = 'myshop')),
    path('account/', include('account.urls', namespace='account')),
    path('order/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('api/', include('api.urls', namespace='api'))






]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]

class CardAddProductFrom(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.views.decorators.http import require_POST
from myshop.models import Product
from .cart import Cart
from .forms import CardAddProductFrom
from coupons.forms import CouponApplyForm


# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id)
    form = CardAddProductFrom(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:c')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:c')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CardAddProductFrom(initial={'quantity':item['quantity'], 'update':True})
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart':cart, 'coupon_apply_form':coupon_apply_form})

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
Koszyk na zakupy
{% endblock %}

{% block content %}
<h1>Koszyk na zakupy</h1>
<table class="cart">
    <thead>
        <tr>
            <th>Obraz</th>
            <th>Produkt</th>
            <th>Ilość</th>
            <th>Usuń</th>
            <th>Cena jednostkowa</th>
            <th>Kwota</th>
        </tr>
    </thead>

    <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}"width="50px"/>{% else %}
                            {% static 'img/no_image.png'%}{% endif %}">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>{{ item.quantity }}</td>
                    <td>
                        <form action="{% url 'cart:card_add' product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Przelicz">
                            {% csrf_token %}
                        </form>
                    </td>
                <td><a href="{% url 'cart:cart_remove' product.id %}">Usuń</a></td>
                <td class="num">{{ item.price }} zł</td>
                <td class="num">{{ item.total_price }} zł</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            {% if cart.coupon %}
                <tr class="subtotal">
                    <td>Wartość całkowita</td>
                    <td colspan="4"></td>
                    <td class="num">{{ cart.get_total_price }} zł.</td>
                </tr>
                <tr>
                    <td>
                        Kupon "{{ cart.coupon.code }}"
                        ({{ cart.coupon.discount }}% rabatu)
                    </td>
                    <td colspan="4"></td>
                    <td class="num neg">
                        -{{ cart.get_discount|floatformat:'2' }} zł
                    </td>
                </tr>
            {% endif %}
            <tr class="total">
                <td>Kwota do zapłaty</td>
                <td colspan="4"></td>
                <td class="num">
                    {{ cart.get_total_price_after_discount|floatformat:'2'}} zł
                </td>
            </tr>
    </tbody>
</table>
<p>Kupon rabatowy:</p>
    <form action="{% url 'coupons:apply' %}" method="post">
        {{ coupon_apply_form }}
        <input type="submit" value="Wprowadź">
        {% csrf_token %}
    </form>
<p class="text-right">
    <a href="{% url 'myshop:product_list' %}" class='button-light'>Kontynuj zakupy</a>
    <a href="{% url 'orders:order_create' %}" class="button">Do kasy</a>
</p>
{% endblock %}