api/urls.py
from django.urls import path

from api.views import ProductListView, ProductDetailView
app_name ='api'

urlpatterns = [
    path('products/', ProductListView.as_view(), name='product_list_api'),
    path('products/<pk>', ProductDetailView.as_view(), name='product_detail_api')
]

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='c'),
    path('add/<int:product_id>/', views.cart_add, name='card_add'),
    path('remove/<int:product_id>', views.cart_remove, name = 'cart_remove'),
]

myshop/urls.py
from django.urls import path
from . import views


app_name ='myshop'

urlpatterns = [
    path('',views.product_list, name ='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('tag/<slug:tag_slug>/', views.product_list, name='product_list_by_tag'),
    path('like/', views.product_like, name='product_like'),


]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from myshop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('myshop.urls', namespace = 'myshop')),
    path('account/', include('account.urls', namespace='account')),
    path('order/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('api/', include('api.urls', namespace='api'))






]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from taggit.managers import TaggableManager
from django.urls import reverse
# Create your models here

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)


    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myshop:product_list_by_category', args=[self.slug])




class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = TaggableManager()
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)
    number_of_products = models.PositiveIntegerField()

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myshop:product_detail', args=[self.id, self.slug])
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
            super(Product, self).save(*args, **kwargs)


class Pictrue(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    pictrue = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

myshop/forms.py
from django import forms


class SearchProductFrom(forms.Form):
    query = forms.CharField(max_length=200, label='Szukaj')

myshop/views.py
from PIL.ImagePalette import random
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import SearchVector
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.decorators.http import require_POST
from django.views.generic import FormView
from taggit.models import Tag
from cart.cart import Cart
from orders.models import Order, OrderItem
from .forms import SearchProductFrom
from taggit.models import Tag
from .models import Category, Product, Pictrue
from cart.forms import CardAddProductFrom
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def product_list(request, category_slug=None, tag_slug=None):
    category = None
    tag = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])

    paginator = Paginator(products, 3)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    return render(request, 'myshop/list.html',
                  context={'category': category, 'categories': categories, 'products': products, 'page': page, 'tag': tag})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    pictrues = Pictrue.objects.filter(product_id=product)
    cart_product_form = CardAddProductFrom()
    return render(request, 'myshop/detail.html', context={'product': product, 'cart_product_form': cart_product_form, 'pictrues': pictrues})

@login_required
@require_POST
def product_like(request):
    product_id = request.POST.get('id')
    action = request.POST.get('action')
    if product_id and action:
        try:
            product = Product.objects.get(id=product_id)
            if action == 'like':
                product.users_like.add(request.user)
            else:
                product.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except:
            pass
    return JsonResponse({'status': 'ok'})

myshop/templates/myshop/detail.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
    {% if category %}
        {{ category.title }}
        {% else %}
        Produkty
    {% endif %}
{% endblock %}

{% block content %}
    <div class="product-detail">

        {% for pictrue in pictrues%}
    {% if pictrue.pictrue %}<img src="{{ pictrue.pictrue.url }}"width="350px"/>{% endif %}
    {% endfor %}

    <h1>{{ product.name }}</h1>
    {% with total_likes=product.users_like.count users_like=product.users_like.all %}
        <div class="product-info">
        <div>
            <span class="count">
                <span class="total">{{ total_likes }}</span> polubień
            </span>
            <a href="#" data-id="{{ product.id }}" data-actions-icnt="{% if request.user in users_like %}
            un{% endif %}like" class="like-button">{% if request.user not in users_like %}
                Lubię
                {% else %}
            Nie lubię
            {% endif %}
            </a>

        </div>
        </div>
    {% endwith %}
    <div class="tag">
    {% for tag in product.tags.all %}
        <a href="{% url 'myshop:product_list_by_tag' tag.slug %}"> {{ tag.name }}</a>
    {% endfor %}
    </div>
    <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a> </h2>
    <p class="price">{{ product.price }} zł</p>
    <p class="count">{{ product.number_of_products }}</p>
    {{ product.description|linebreaks }}
    <form action="{% url 'cart:card_add' product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Dodaj do koszyka">
    </form>
    </div>
{% endblock %}

myshop/templates/myshop/list.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
    {% if category %}
        {{ category.name }}

    {% else %}
        Produkty
    {% endif %}
{% endblock %}

{% block content %}
<div id="sidebar">
    <h3>Kategorie</h3>
    <ul>
        <li {% if not category %} class="selected"{% endif %}>
        <a href="{% url 'myshop:product_list' %}">Wszystkie</a>
        </li>
    {% for cat in categories %}
        <li {% if category.slug == cat.slug %} class="selected"{% endif %}>
            <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
        </li>

    {% endfor %}
    </ul>
</div>
<div id="content-main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Produkty{% endif %} </h1>
    {% for product in products %}
        <div class="item">
            <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }}"width='250px'>{% else %}
                {% static 'img/no_image.png'%}{% endif %}">
            </a>
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
            {{ product.price }} zł
        </div>
        <hr>
    {% endfor %}

</div>
    {% include 'myshop/pagination.html' with page=products %}
{% endblock %}

myshop/templates/myshop/pagination.html
<div class="paginator">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Poprzednia</a>
        {% endif %}
        <span class="current>">
            Strona {{ page.number }} z {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Nastepna</a>
        {% endif %}
    </span>
</div>