api/urls.py
from django.urls import path

from api.views import ProductListView, ProductDetailView
app_name ='api'

urlpatterns = [
    path('products/', ProductListView.as_view(), name='product_list_api'),
    path('products/<pk>', ProductDetailView.as_view(), name='product_detail_api')
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('history-order/', views.orders_history, name='history'),
    path('detail-order/<int:id>', views.detail_order, name='detail_order')




]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from myshop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('myshop.urls', namespace = 'myshop')),
    path('account/', include('account.urls', namespace='account')),
    path('order/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('api/', include('api.urls', namespace='api'))






]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.contrib.auth.models import User
from django.db import models
from myshop.models import Product

# Create your models here.

class Order(models.Model):
    first_name = models.CharField(max_length=50, null=True)
    last_name = models.CharField(max_length=50, null=True)
    email = models.EmailField(null=True)
    adress = models.CharField(max_length=250, null=True)
    postal_code = models.PositiveIntegerField(null=True)
    city = models.CharField(max_length=100, null=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    phone = models.PositiveIntegerField(null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.id}'

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order
from localflavor.pl.forms import PLPostalCodeField


class OrderCreateForm(forms.ModelForm):
    postal_code = PLPostalCodeField()
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'adress', 'city', 'phone', 'postal_code']

orders/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import Http404
from django.shortcuts import render

from myshop.models import Product
from .models import OrderItem, Order
from .forms import OrderCreateForm
from cart.cart import Cart


# Create your views here.

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.owner = request.user
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'],
                                         )
            cart.clear()
        return render(request, 'orders/order/created.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order/create.html', {'cart':cart, 'form':form})



@login_required()
def orders_history(request):
    orders = Order.objects.filter(owner=request.user).order_by('-created')
    return render(request, 'orders/order/history.html', {'orders':orders})

@login_required()
def detail_order(request, id):
    order = Order.objects.get(pk=id)
    items = OrderItem.objects.filter(order_id=order)
    if order.owner != request.user:
        raise Http404
    return render(request, 'orders/order/detail.html',context={'order': order, 'items': items})

orders/templates/orders/order/create.html
{% extends 'shop/base.html' %}

{% block title %}
Kasa
{% endblock %}

{% block content %}
<h1>Kasa</h1>
    <div class="order-info">
        <h3>Zamówienie</h3>
        <ul>
        {% for item in cart %}
            <li>
                {{ item.quantity }}X {{ item.product.name }}
            <span>{{ item.total_price }} zł</span>
            </li>
        {% endfor %}
        {% if cart.coupon %}
            <li>
                Kupon "{{ cart.coupon.code }}" ({{ cart.coupon.discount }}% rabatu)
            <span>{{ cart.get_discount|floatformat:'2' }} zł</span>
            </li>
        {% endif %}
        </ul>
        <p>Wartość całkowita:{{ cart.get_total_price }} zł</p>
    </div>

<form action="." method="post" class="order-form">
    {{ form.as_p }}
    <p><input type="submit" value="Złóż zamówienie"></p>
    {% csrf_token %}
</form>
{% endblock %}

orders/templates/orders/order/created.html
{% extends 'shop/base.html' %}

{% block title %}
Dziękujemy
{% endblock %}


{% block content %}
    <h1>Dziekujemy</h1>
    <p>Zamówienie zostało złożone, a jego numer to <strong>{{ order.id }}</strong>.</p>
{% endblock %}

orders/templates/orders/order/detail.html
{% extends 'shop/base.html' %}

{% block title %}
Szczegóły zamówienia
{% endblock %}

{% block content %}
    <p>Dane zamawiającego</p>
    <p>Imię: {{ order.first_name }}</p>
    <p>Nazwisko: {{ order.last_name }}</p>
    <p>Nr. tel:{{ order.phone }}</p>
    <p>Miasto: {{ order.city }}</p>
    <p>Kod pocztowy: {{ order.postal_code }}</p>
    <p>Adres: {{ order.adress }}</p>
    <p></p>
    <p>Wartość całego zamówienia: {{ order.get_total_cost }}</p>
    <p>Opłacone: {{ order.paid }}</p>
    <p>
    {% for item in items %}
        <p>Produkt:<a href="{{ item.product.get_absolute_url }}"> {{ item.product }}</a></p>
        <p>Cena za szt.: {{ item.price }}</p>
        <p>Ilość: {{ item.quantity }}</p>
        <ul><a href="{{ item.product.get_absolute_url }}">{% if item.product.image %}<img src="{{ item.product.image.url }}"width="50px"/>{% endif %}</a></ul>

    {% endfor %}

    </p>


{% endblock %}

orders/templates/orders/order/history.html
{% extends 'shop/base.html' %}

{% block title %}
Historia zamówień
{% endblock %}

{% block content %}

<style> td { border: 1px solid black; } </style>

    <table>
   <tr>
      <td>Data zamówienia</td> <td> Suma zamówienia</td> <td>Płatność</td><td>Szczegóły zamówienia</td>
   </tr>
        {% for order in orders %}
   <tr>
      <td>{{ order.created }}</td> <td>{{ order.get_total_cost }}</td> <td>{{ order.paid }}</td>
       <td><a href="{% url 'orders:detail_order' order.id %}">Szczegóły zamówienia</a></td>

   </tr>

    {% endfor %}
</table>
{% endblock %}