account/urls.py
from django.urls import path
from . import views
from account.views import Register

app_name = 'account'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', Register.as_view(), name='register'),
    path('user/', views.user_detail, name='user'),
    path('edit/', views.edit_user, name='edit-user'),

]

api/urls.py
from django.urls import path

from api.views import ProductListView, ProductDetailView
app_name ='api'

urlpatterns = [
    path('products/', ProductListView.as_view(), name='product_list_api'),
    path('products/<pk>', ProductDetailView.as_view(), name='product_detail_api')
]

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='c'),
    path('add/<int:product_id>/', views.cart_add, name='card_add'),
    path('remove/<int:product_id>', views.cart_remove, name = 'cart_remove'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from myshop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('myshop.urls', namespace = 'myshop')),
    path('account/', include('account.urls', namespace='account')),
    path('order/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('api/', include('api.urls', namespace='api'))






]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Mój sklep{% endblock %}</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
    <div id="header">
        <a href="/" class="logo">Mój sklep</a>
    </div>
    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    Koszyk:
                        <a href="{% url 'cart:c' %}">
                        {{ total_items }} produkt{{ total_items|pluralize:'y' }},
                        {{ cart.get_total_price }} zł
                        </a>
                {% else %}
                    Koszyk jest pusty.
                {% endif %}
            {% endwith %}
        </div>
        <span class="user">
            <div>
            {% if request.user.is_authenticated %}
                Witaj <a href="{% url 'account:user'%}" >{{ request.user.first_name }}</a>
                <a href="{% url 'account:logout' %}">Wyloguj</a>

            {% else %}
                <ul><a href="{% url 'account:login' %}">Zaloguj</a></ul>
                <ul><a href="{% url 'account:register' %}">Załóż konto</a></ul>
            {% endif %}
{% block edit_user %}

{% endblock %}
            </div>
        </span>
    </div>
    <div id="content">
    {% if random_products %}
        {% for product in random_products %}
            <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }}"
              width='100px'>{% else %}{% static 'img/no_image.png' %}{% endif %} >
            </a>
        {% endfor %}
        
    {% endif %} 
    
        {% block content %}

        {% endblock %}
    </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1./jquery.min.js"></script>
<script src="https://cdn.jsdeliver.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script>
    var crsftoken = $.cookie('crsftoken');
    function crsfSafeMethod {
        return(/^(GET|HEAD|OPTIONS|TRACE)$/.test(method)):
    }
    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!crsfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("H-CRSFToken", crsftoken);
            }
        }
    });
    $(document).ready(function () {
        {% block domready %}

        {% endblock %}
    });
</script>
</body>
</html>